version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestBugBashProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.testbugbash.integrations:t
  packages:
  - name: TestBugBashProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
